sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t gaddiego/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true gaddiego/react-test npm test

after_success:
  - docker build -t gaddiego/multi-client ./client
  - docker build -t gaddiego/multi-nginx ./nginx
  - docker build -t gaddiego/multi-server ./server
  - docker build -t gaddiego/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password_stdin
  - docker push gaddiego/multi-client
  - docker push gaddiego/multi-nginx
  - docker push gaddiego/multi-server
  - docker push gaddiego/multi-worker
  
deploy:
    provider: elasticbeanstalk
    region: eu-north-1
    app: multi-docker-2
    env: Multi-docker-2-env
    bucket_name: elasticbeanstalk-us-east-1-108782091232
    bucket_path: multi_docker
    ok:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: 
        secure: $AWS_SECRET_KEY