sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t gaddiego/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true gaddiego/react-test npm test

after_success:
  - docker build -t gaddiego/multi-client ./client
  - docker build -t gaddiego/multi-nginx ./nginx
  - docker build -t gaddiego/multi-server ./server
  - docker build -t gaddiego/multi-worker ./worker

